Minimal/Starterkit/dashboards/urls.py
from django.urls import path
from dashboards.views import (
    dashboard_view,

)

app_name = 'dashboards'

urlpatterns = [
    path('',view =dashboard_view,name="dashboard"),    
]

Minimal/Starterkit/pages/urls.py
from django.urls import path
from pages.views import (
authentication_signin_basic,
authentication_signin_cover,
authentication_signup_basic,
authentication_signup_cover,
authentication_pass_reset_basic,
authentication_pass_reset_cover,
authentication_lockscreen_basic,
authentication_lockscreen_cover,
authentication_logout_basic,
authentication_logout_cover,
authentication_success_msg_basic,
authentication_success_msg_cover,
authentication_twostep_basic,
authentication_twostep_cover,
authentication_404_basic,
authentication_404_cover,
authentication_404_alt,
authentication_500,
pages_starter,

)

app_name = "pages"

urlpatterns = [
    # Authentication
    path("authentication/signin-basic",view =authentication_signin_basic,name="authentication.signin_basic"),
    path("authentication/signin-cover",view =authentication_signin_cover,name="authentication.signin_cover"),
    path("authentication/signup-basic",view =authentication_signup_basic,name="authentication.signup_basic"),
    path("authentication/signup-cover",view =authentication_signup_cover,name="authentication.signup_cover"),
    path("authentication/password-reset-basic",view =authentication_pass_reset_basic,name="authentication.pass_reset_basic"),
    path("authentication/password-reset-cover",view =authentication_pass_reset_cover,name="authentication.pass_reset_cover"),
    path("authentication/lockscreen-basic",view =authentication_lockscreen_basic,name="authentication.lockscreen_basic"),
    path("authentication/lockscreen-cover",view =authentication_lockscreen_cover,name="authentication.lockscreen_cover"),
    path("authentication/logout-basic",view =authentication_logout_basic,name="authentication.logout_basic"),
    path("authentication/logout-cover",view =authentication_logout_cover,name="authentication.logout_cover"),
    path("authentication/success-msg-basic",view =authentication_success_msg_basic,name="authentication.success_msg_basic"),
    path("authentication/success-msg-cover",view =authentication_success_msg_cover,name="authentication.success_msg_cover"),
    path("authentication/two-step-authentication-basic",view =authentication_twostep_basic,name="authentication.twostep_basic"),
    path("authentication/two-step-authentication-cover",view =authentication_twostep_cover,name="authentication.twostep_cover"),
    path("authentication/404-basic",view =authentication_404_basic,name="authentication.404_basic"),
    path("authentication/404-cover",view =authentication_404_cover,name="authentication.404_cover"),
    path("authentication/404-alt",view =authentication_404_alt,name="authentication.404_alt"),
    path("authentication/500",view =authentication_500,name="authentication.500"),
    
    # Pages
    path("pages/starter-page",view =pages_starter,name="pages.starter"),
    
] 

Minimal/Starterkit/velzon/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.decorators import login_required
from .views import MyPasswordChangeView, MyPasswordSetView
urlpatterns = [
    path('admin/', admin.site.urls),
    # Dashboard
    path('',include('dashboards.urls')),
    # Layouts
    path('layouts/',include('layouts.urls')),
    # Pages
    path('pages/',include('pages.urls')),
    path("account/password/change/",login_required(MyPasswordChangeView.as_view()),name="account_change_password"),
    path("account/password/set/",login_required(MyPasswordSetView.as_view()),name="account_set_password"),
    # All Auth 
    path('account/', include('allauth.urls')),
]

Minimal/Starterkit/templates/pages/pages-coming-soon.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg">
<head>
    <meta charset="utf-8" />
    <title>Coming Soon | Velzon - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

    <!-- Layout config Js -->
    <script src="{% static 'js/layout.js'%}"></script>
    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    <!-- custom Css-->
    <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="auth-page-wrapper pt-5">
        <!-- auth page bg -->
        <div class="auth-one-bg-position auth-one-bg"  id="auth-particles">
            <div class="bg-overlay"></div>
            
            <div class="shape">
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1440 120">
                    <path d="M 0,36 C 144,53.6 432,123.2 720,124 C 1008,124.8 1296,56.8 1440,40L1440 140L0 140z"></path>
                </svg>
            </div>
        </div>

        <!-- auth page content -->
        <div class="auth-page-content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center mt-sm-5 pt-4 mb-4">
                            <div class="mb-sm-5 pb-sm-4 pb-5">
                                <img src="{% static 'images/comingsoon.png'%}" alt="" height="120" class="move-animation">
                            </div>
                            <div class="mb-5">
                                <h1 class="display-2 coming-soon-text">Coming Soon</h1>
                            </div>
                            <div>
                                <div class="row justify-content-center mt-5">
                                    <div class="col-lg-8">
                                        <div id="countdown" class="countdownlist"></div>
                                    </div>
                                </div>

                                <div class="mt-5">
                                    <h4>Get notified when we launch</h4>
                                    <p class="text-muted">Don't worry we will not spam you 😊</p>
                                </div>

                                <div class="input-group countdown-input-group mx-auto my-4">
                                    <input type="email" class="form-control border-light shadow" placeholder="Enter your email address" aria-label="search result" aria-describedby="button-email">
                                    <button class="btn btn-success" type="button" id="button-email">Send<i class="ri-send-plane-2-fill align-bottom ms-2"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->

            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->

        <!-- footer -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">
                            <p class="mb-0 text-muted">&copy; <script>document.write(new Date().getFullYear())</script> Velzon. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->
    </div>
    <!-- end auth-page-wrapper -->

    <!-- JAVASCRIPT -->
    <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'libs/simplebar/dist/simplebar.min.js'%}"></script>
    <script src="{% static 'libs/node-waves/dist/waves.min.js'%}"></script>
    <script src="{% static 'libs/feather-icons/dist/feather.min.js'%}"></script>
    <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>
    <!-- particles js -->
    <script src="{% static 'libs/particles.js/particles.js'%}"></script>
    <!-- particles app js -->
    <script src="{% static 'js/pages/particles.app.js'%}"></script>
    <!-- Countdown js -->
    <script src="{% static 'js/pages/coming-soon.init.js'%}"></script>
</body>
</html>

Minimal/Starterkit/templates/pages/pages-maintenance.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg">
<head>
    <meta charset="utf-8" />
    <title>Maintenance | Velzon - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

    <!-- Layout config Js -->
    <script src="{% static 'js/layout.js'%}"></script>
    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    <!-- custom Css-->
    <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="auth-page-wrapper pt-5">
        <!-- auth page bg -->
        <div class="auth-one-bg-position auth-one-bg" id="auth-particles">
            <div class="bg-overlay"></div>
    
            <div class="shape">
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1440 120">
                    <path d="M 0,36 C 144,53.6 432,123.2 720,124 C 1008,124.8 1296,56.8 1440,40L1440 140L0 140z"></path>
                </svg>
            </div>
        </div>
    
        <!-- auth page content -->
        <div class="auth-page-content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center mt-sm-5 pt-4">
                            <div class="mb-5 text-white-50">
                                <h1 class="display-5 coming-soon-text">Site is Under Maintenance</h1>
                                <p class="fs-14">Please check back in sometime</p>
                                <div class="mt-4 pt-2">
                                    <a href="{% url 'dashboards:dashboard'%}" class="btn btn-success"><i class="mdi mdi-home me-1"></i> Back to Home</a>
                                </div>
                            </div>
                            <div class="row justify-content-center mb-5">
                                <div class="col-xl-4 col-lg-8">
                                    <div>
                                        <img src="{% static 'images/maintenance.png'%}" alt="" class="img-fluid">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
    
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->

        <!-- footer -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">
                            <p class="mb-0 text-muted">&copy; <script>document.write(new Date().getFullYear())</script> Velzon. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->
    
    </div>
    <!-- end auth-page-wrapper -->

    <!-- JAVASCRIPT -->
    <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'libs/simplebar/dist/simplebar.min.js'%}"></script>
    <script src="{% static 'libs/node-waves/dist/waves.min.js'%}"></script>
    <script src="{% static 'libs/feather-icons/dist/feather.min.js'%}"></script>
    <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>
    <!-- particles js -->
    <script src="{% static 'libs/particles.js/particles.js'%}"></script>
    <!-- particles app js -->
    <script src="{% static 'js/pages/particles.app.js'%}"></script>

</body>
</html>

Minimal/Starterkit/templates/pages/pages-starter.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}Starter Page{% endblock title %}
{% block content %}
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">

                    {% block pagetitle %}
                    {% include "partials/page-title.html" with pagetitle="Pages" title="Starter" %}
                    {% endblock pagetitle %}

                    
                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->

        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock footer %}
        </div>
        <!-- end main content-->
{% endblock content %}